import java.sql.*;
//import Project.ConnectionProvider;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Project.InsertUpdateDelete;
import Project.Select;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PRAMOD
 */
public class customerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form customerCheckOut
     */
    public customerCheckOut() {
        initComponents();
        
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        //jTextField2.setEditable(false);
        
        
    }
    
    int patientId=0;
    String roomType;
    String bed;
    String roomNo;
    String Query;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Patient Check-Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 47, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 66, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Room Number ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 211, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 208, 131, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 207, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number ", "Nationality", "Gender", "E-Mail", "ID Proof", "Address", "Check-IN", "Room Number", "Bed", "Room Type", "Price Per Day"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 1470, 234));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 290, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Check In Date ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 304, -1, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 357, 320, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Check Out Date (Today) ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 320, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Patient Mobile Number ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 310, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 360, 290, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Price Per Day");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 290, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 521, 320, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Number Days Stay ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 465, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Total Amount to Collect From Customer ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 320, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("E-Mail");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 470, -1, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 520, 290, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Check - Out ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

       
        ResultSet rs=Select.getData("select * from patientCheckIn where checkOut is NULL");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        
        try
        {
             while(rs.next())
                {
                    model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13) });
                    
                }
                rs.close();
        }
        catch(Exception e)
        {
            
        }
        /* try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
            ResultSet rs =st.executeQuery("select * from patientCheckIn where checkOut is NULL");
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            
            try
            {
                
                while(rs.next())
                {
                    model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13) });
                    
                }
                rs.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
                  
        }
        catch(Exception e)
        {
            
        }*/
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String roomNo=jTextField1.getText();
        
        try
        {
           
            ResultSet rs=Select.getData( "select * from patientCheckIn where roomNo='"+roomNo+"' and checkout is NULL");
            
             if(rs.next())
            {
                jTextField1.setEditable(false);
                patientId=rs.getInt(1);
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(9));
                jTextField5.setText(rs.getString(3));
                jTextField6.setText(rs.getString(13));
                
                SimpleDateFormat myFormat=new SimpleDateFormat("dd/MM/yyyy");
                Calendar cal=Calendar.getInstance();
                
                jTextField4.setText(myFormat.format(cal.getTime()));
                
                String dateBeforeString=rs.getString(9);
                
                java.util.Date dateBefore=myFormat.parse(dateBeforeString);
                
                String dateAfterString=myFormat.format(cal.getTime());
               
                java.util.Date dateAfter=myFormat.parse(dateAfterString);
                long difference=dateAfter.getTime() - dateBefore.getTime();
                int noOfDayStay=(int) (difference/((1000*60*60*24)));//Ths is for num of day stay
                
                if(noOfDayStay==0)
               {
                   noOfDayStay=1;
                   jTextField7.setText(String.valueOf(noOfDayStay));
                   float price = Float.parseFloat(jTextField6.getText());
                   
                   jTextField8.setText(String.valueOf(noOfDayStay*price));
                   jTextField9.setText(rs.getString(6));
                   roomType=rs.getString(12);
                   bed=rs.getString(11);
               }
               else
               {
                   JOptionPane.showMessageDialog(null,"Ward Number not booked or Room Number is Does Not Exists");
               }
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
       /* try
        {
            
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
            ResultSet rs =st.executeQuery("select * from patientCheckIn where roomNo='"+roomNo+"' and checkout is NULL");
            
            if(rs.next())
            {
                jTextField1.setEditable(false);
                patientId=rs.getInt(1);
                jTextField2.setText(rs.getString(2));
                jTextField3.setText(rs.getString(9));
                jTextField5.setText(rs.getString(3));
                jTextField6.setText(rs.getString(13));
                
                SimpleDateFormat myFormat=new SimpleDateFormat("dd/MM/yyyy");
                Calendar cal=Calendar.getInstance();
                
                jTextField4.setText(myFormat.format(cal.getTime()));
                
                String dateBeforeString=rs.getString(9);
                
               java.util.Date dateBefore=myFormat.parse(dateBeforeString);
               
               String dateAfterString=myFormat.format(cal.getTime());
               
               java.util.Date dateAfter=myFormat.parse(dateAfterString);
               long difference=dateAfter.getTime() - dateBefore.getTime();
               int noOfDayStay=(int) (difference/((1000*60*60*24)));
               
               if(noOfDayStay==0)
               {
                   noOfDayStay=1;
                   jTextField7.setText(String.valueOf(noOfDayStay));
                   float price = Float.parseFloat(jTextField6.getText());
                   
                   jTextField8.setText(String.valueOf(noOfDayStay*price));
                   jTextField9.setText(rs.getString(6));
                   roomType=rs.getString(12);
                   bed=rs.getString(11);
               }
               else
               {
                   JOptionPane.showMessageDialog(null,"Ward Number is not booked or Room Number is Does Not Exists");
               }
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
        setVisible(false);
        new customerCheckOut().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String name=jTextField2.getText();
        String mobileNumber=jTextField5.getText();
        String email=jTextField9.getText();
        
        String checkOut=jTextField4.getText();
        String numberOfDaysStay=jTextField7.getText();
        String totalAmount=jTextField8.getText();
        roomNo=jTextField1.getText();
        
        Query="update  patientcheckin set numberOfDaysStay='"+numberOfDaysStay+"', totalAmount='"+totalAmount+"', checkOut='"+checkOut+"' where patientId='"+patientId+"' ";
        
        InsertUpdateDelete.setData(Query,"");
        
        Query="update room set Status='Not Booked' where roomNo='"+roomNo+"'";
        
        InsertUpdateDelete.setData(Query,"");
         String path="E:\\";
         
         
         com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
         
         try
            {
               PdfWriter.getInstance(doc, new FileOutputStream(path+""+patientId+".pdf"));
               doc.open();
               Paragraph paragraph1=new Paragraph("                  Hospital Management System");
               doc.add(paragraph1);
               
               Paragraph paragraph2=new Paragraph("*********************************************************************************************************************************");
               doc.add(paragraph2);
               
               Paragraph paragraph3=new Paragraph("\tBill ID : "+patientId+"\nPatient Details:\nName: "+name+"\nMobile Number : "+mobileNumber+"\nE-Mail: "+email+"\n");
               doc.add(paragraph3);
               
               doc.add(paragraph2);
               
               Paragraph paragraph4=new Paragraph("\t Room Details : \nNumber :"+jTextField1.getText()+"\nType :"+roomType+"\nBed : "+bed+"\nPrice Per Day :"+jTextField6.getText()+"");
               doc.add(paragraph4);
               
               doc.add(paragraph2);
               
               PdfPTable tb1 = new PdfPTable(4);
               tb1.addCell("Check-In Date : "+jTextField3.getText());
               tb1.addCell("Check-Out Date : "+checkOut);
               tb1.addCell("Num Of Days Stay  : "+numberOfDaysStay);
               tb1.addCell("Total Amount Paid  : "+totalAmount);
               doc.add(tb1);
               
               doc.add(paragraph2);
               
               Paragraph paragraph5=new Paragraph("Thank You , Please Visit Again ");
               doc.add(paragraph5);
               
               
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
         doc.close();
         int a=JOptionPane.showConfirmDialog(null, "Do You Want to Print The Bill","select",JOptionPane.YES_NO_OPTION);
            
            if(a==0)
            {
                try
                {
                    
                    if((new File("E:\\"+patientId+".pdf")).exists())
                    {
                        Process p= Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler E:\\"+patientId+".pdf");
                        
                    }
                    else
                    {
                        System.out.println("File is Not Exists");
                    }
                    
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
            }
            setVisible(false);
            new customerCheckOut().setVisible(true);
            
         
         
         
        
       /* try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
            int rs =st.executeUpdate("update  patientcheckin set numberOfDaysStay='"+numberOfDaysStay+"', totalAmount='"+totalAmount+"', checkOut='"+checkOut+"' where patientId='"+patientId+"' ");
             
            st.executeUpdate("update room set Status='Not Booked' where roomNo='"+roomNo+"'");
            
            JOptionPane.showMessageDialog(null, "Check-Out Successfully Collect The Amount");
            
            String path="E:\\";
        }                          //Extra
        catch(Exception e)         //Extra
        {                         //Extra    
               
        }                          //Extra
            */
            /*com.itextpdf.awt.text.Document doc = new com.itextpdf.awt.text.Document();
            try
            {
               PdfWriter.getInstance(doc, new FileOutputStream(path+""+patientId+".pdf"));
               doc.open();
               Paragraph paragraph1=new Paragraph("                  Hospital Management System");
               doc.add(paragraph1);
               
               Paragraph paragraph2=new Paragraph("*********************************************************************************************************************************");
               doc.add(paragraph2);
               
               Paragraph paragraph3=new Paragraph("\tBill ID : "+patientId+"\nPatient Details:\nName: "+name+"\nMobile Number : "+mobileNumber+"\nE-Mail: "+email+"\n");
               doc.add(paragraph3);
               
               doc.add(paragraph2);
               
               Paragraph paragraph4=new Paragraph("\t Room Details : \nNumber :"+jTextField1.getText()+"\nType :"+roomType+"\nBed : "+bed+"\nPrice Per Day :"+jTextField6.getText()+"");
               doc.add(paragraph4);
               
               doc.add(paragraph2);
               
               PdfPTable tb1 = new PdfPTable(4);
               tb1.addCell("Check-In Date : "+jTextField3.getText());
               tb1.addCell("Check-Out Date : "+checkOut);
               tb1.addCell("Num Of Days Stay  : "+numberOfDaysStay);
               tb1.addCell("Total Amount Paid  : "+totalAmount);
               
               doc.add(paragraph2);
               
               Paragraph paragraph5=new Paragraph("Thank You , Please Visit Again ");
               doc.add(paragraph5);
               
               
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
            
            doc.close();
            int a=JOptionPane.showConfirmDialog(null, "Do You Want to Print The Bill","select",JOptionPane.YES_NO_OPTION);
            
            if(a==0)
            {
                try
                {
                    
                    if((new File("E:\\"+patientId+".pdf")).exists())
                    {
                        Process p= Runtime.getRuntime().exec("rundl132 url.dll,FileProtocolHandler E:\\"+patientId+".pdf");
                        
                    }
                    else
                    {
                        System.out.println("File is Not Exists");
                    }
                    
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
            }
            setVisible(false);
            new customerCheckOut().setVisible(true);
            
         }
        catch(Exception e)
        {
            
        }*/
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
